[platformio]
default_envs = node_b_master ; Ubah ini ke node_a_slave jika ingin defaultnya kapal
;default_envs = node_a_slave ; Ubah ini ke node_a_slave jika ingin defaultnya kapal

[env]
platform = espressif32@6.8.0
board = esp32dev
framework = espidf
monitor_speed = 115200
monitor_filters = direct

[env:node_a_slave]
build_flags = 
    -D COMPILE_NODE_A
    -D COMPILE_MINSIS ; Ganti ke COMPILE_MINSIS jika Node A pakai PCB custom

[env:node_b_master]
build_flags = 
    -D COMPILE_NODE_B
    -D COMPILE_BREADBOARD